import { Category } from "@/backend.d";
import type { MenuItem } from "@/backend.d";

// Complete menu data with AI-generated images
export const SEED_MENU_ITEMS: Omit<MenuItem, "id">[] = [
  // Indian Main Course
  {
    name: "Paneer Butter Masala",
    description: "Cottage cheese in rich tomato and butter gravy",
    price: 180n,
    category: Category.indianMainCourse,
    imageUrl: "/assets/generated/paneer-butter-masala.dim_800x600.jpg",
    available: true,
  },
  {
    name: "Dal Makhani",
    description: "Black lentils slow-cooked in creamy tomato gravy",
    price: 150n,
    category: Category.indianMainCourse,
    imageUrl: "/assets/generated/dal-makhani.dim_800x600.jpg",
    available: true,
  },
  {
    name: "Butter Chicken",
    description: "Tender chicken in creamy tomato-based curry",
    price: 220n,
    category: Category.indianMainCourse,
    imageUrl: "/assets/generated/butter-chicken.dim_800x600.jpg",
    available: true,
  },
  {
    name: "Kadai Paneer",
    description: "Paneer cooked with bell peppers and onions in kadai masala",
    price: 170n,
    category: Category.indianMainCourse,
    imageUrl: "/assets/generated/kadai-paneer.dim_800x600.jpg",
    available: true,
  },
  {
    name: "Palak Paneer",
    description: "Cottage cheese in smooth spinach gravy",
    price: 170n,
    category: Category.indianMainCourse,
    imageUrl: "/assets/generated/palak-paneer.dim_800x600.jpg",
    available: true,
  },
  {
    name: "Shahi Paneer",
    description: "Royal paneer curry in rich cashew-based gravy",
    price: 190n,
    category: Category.indianMainCourse,
    imageUrl: "/assets/generated/shahi-paneer.dim_800x600.jpg",
    available: true,
  },
  {
    name: "Mix Veg",
    description: "Mixed vegetables cooked in flavorful curry",
    price: 140n,
    category: Category.indianMainCourse,
    imageUrl: "/assets/generated/mix-veg.dim_800x600.jpg",
    available: true,
  },
  {
    name: "Aloo Gobi",
    description: "Potato and cauliflower cooked with aromatic spices",
    price: 130n,
    category: Category.indianMainCourse,
    imageUrl: "/assets/generated/aloo-gobi.dim_800x600.jpg",
    available: true,
  },
  {
    name: "Chicken Curry",
    description: "Traditional chicken curry with aromatic spices",
    price: 200n,
    category: Category.indianMainCourse,
    imageUrl: "/assets/generated/chicken-curry.dim_800x600.jpg",
    available: true,
  },
  {
    name: "Mutton Rogan Josh",
    description: "Tender mutton in aromatic Kashmiri gravy",
    price: 280n,
    category: Category.indianMainCourse,
    imageUrl: "/assets/generated/mutton-rogan-josh.dim_800x600.jpg",
    available: true,
  },

  // Chinese
  {
    name: "Chilli Paneer",
    description: "Crispy paneer tossed in spicy Indo-Chinese sauce",
    price: 170n,
    category: Category.chinese,
    imageUrl: "/assets/generated/chilli-paneer.dim_800x600.jpg",
    available: true,
  },
  {
    name: "Veg Manchurian",
    description: "Vegetable balls in tangy Manchurian sauce",
    price: 150n,
    category: Category.chinese,
    imageUrl: "/assets/generated/veg-manchurian.dim_800x600.jpg",
    available: true,
  },
  {
    name: "Hakka Noodles",
    description: "Stir-fried noodles with vegetables",
    price: 140n,
    category: Category.chinese,
    imageUrl: "/assets/generated/hakka-noodles.dim_800x600.jpg",
    available: true,
  },
  {
    name: "Veg Fried Rice",
    description: "Fried rice with mixed vegetables",
    price: 130n,
    category: Category.chinese,
    imageUrl: "/assets/generated/veg-fried-rice.dim_800x600.jpg",
    available: true,
  },
  {
    name: "Chicken Fried Rice",
    description: "Fried rice with juicy chicken pieces",
    price: 160n,
    category: Category.chinese,
    imageUrl: "/assets/generated/chicken-fried-rice.dim_800x600.jpg",
    available: true,
  },
  {
    name: "Schezwan Noodles",
    description: "Spicy Schezwan-style noodles",
    price: 150n,
    category: Category.chinese,
    imageUrl: "/assets/generated/schezwan-noodles.dim_800x600.jpg",
    available: true,
  },

  // Biryani
  {
    name: "Chicken Biryani",
    description: "Fragrant basmati rice with tender chicken",
    price: 180n,
    category: Category.riceBiryani,
    imageUrl: "/assets/generated/chicken-biryani.dim_800x600.jpg",
    available: true,
  },
  {
    name: "Veg Biryani",
    description: "Aromatic rice with mixed vegetables and spices",
    price: 150n,
    category: Category.riceBiryani,
    imageUrl: "/assets/generated/veg-biryani.dim_800x600.jpg",
    available: true,
  },
  {
    name: "Mutton Biryani",
    description: "Rich biryani with succulent mutton pieces",
    price: 250n,
    category: Category.riceBiryani,
    imageUrl: "/assets/generated/mutton-biryani.dim_800x600.jpg",
    available: true,
  },
  {
    name: "Egg Biryani",
    description: "Flavorful biryani with boiled eggs",
    price: 140n,
    category: Category.riceBiryani,
    imageUrl: "/assets/generated/egg-biryani.dim_800x600.jpg",
    available: true,
  },

  // Tandoori (Breads)
  {
    name: "Tandoori Roti",
    description: "Traditional whole wheat flatbread from tandoor",
    price: 15n,
    category: Category.tandooriRoti,
    imageUrl: "/assets/generated/tandoori-roti.dim_800x600.jpg",
    available: true,
  },
  {
    name: "Butter Naan",
    description: "Soft leavened bread brushed with butter",
    price: 30n,
    category: Category.tandooriRoti,
    imageUrl: "/assets/generated/butter-naan.dim_800x600.jpg",
    available: true,
  },
  {
    name: "Garlic Naan",
    description: "Naan topped with fresh garlic and coriander",
    price: 40n,
    category: Category.tandooriRoti,
    imageUrl: "/assets/generated/garlic-naan.dim_800x600.jpg",
    available: true,
  },

  // Tandoori (Grilled)
  {
    name: "Tandoori Chicken",
    description: "Marinated chicken grilled in tandoor",
    price: 280n,
    category: Category.tandooriRoti,
    imageUrl: "/assets/generated/tandoori-chicken.dim_800x600.jpg",
    available: true,
  },
  {
    name: "Paneer Tikka",
    description: "Marinated paneer cubes grilled to perfection",
    price: 200n,
    category: Category.tandooriRoti,
    imageUrl: "/assets/generated/paneer-tikka.dim_800x600.jpg",
    available: true,
  },
  {
    name: "Chicken Tikka",
    description: "Boneless chicken marinated in spices and grilled",
    price: 240n,
    category: Category.tandooriRoti,
    imageUrl: "/assets/generated/chicken-tikka.dim_800x600.jpg",
    available: true,
  },

  // Thali
  {
    name: "Veg Thali",
    description: "Complete meal with 2 veg curries, dal, rice, roti, salad & dessert",
    price: 180n,
    category: Category.thali,
    imageUrl: "/assets/generated/veg-thali.dim_800x600.jpg",
    available: true,
  },
  {
    name: "Non-Veg Thali",
    description: "Complete meal with chicken curry, dal, rice, roti, salad & dessert",
    price: 250n,
    category: Category.thali,
    imageUrl: "/assets/generated/non-veg-thali.dim_800x600.jpg",
    available: true,
  },

  // Soya Chaap
  {
    name: "Soya Chaap Tikka",
    description: "Marinated soya chaap grilled in tandoor",
    price: 160n,
    category: Category.soyaChaap,
    imageUrl: "/assets/generated/soya-chaap-tikka.dim_800x600.jpg",
    available: true,
  },
  {
    name: "Soya Chaap Curry",
    description: "Soya chaap in rich creamy gravy",
    price: 170n,
    category: Category.soyaChaap,
    imageUrl: "/assets/generated/soya-chaap-curry.dim_800x600.jpg",
    available: true,
  },

  // Fast Food
  {
    name: "Veg Burger",
    description: "Crispy veg patty with fresh vegetables",
    price: 60n,
    category: Category.fastFood,
    imageUrl: "/assets/generated/veg-burger.dim_800x600.jpg",
    available: true,
  },
  {
    name: "Chicken Burger",
    description: "Juicy chicken patty with cheese and sauce",
    price: 90n,
    category: Category.fastFood,
    imageUrl: "/assets/generated/chicken-burger.dim_800x600.jpg",
    available: true,
  },
  {
    name: "Veg Pizza",
    description: "Pizza topped with fresh vegetables and cheese",
    price: 150n,
    category: Category.fastFood,
    imageUrl: "/assets/generated/veg-pizza.dim_800x600.jpg",
    available: true,
  },
  {
    name: "French Fries",
    description: "Crispy golden french fries",
    price: 80n,
    category: Category.fastFood,
    imageUrl: "/assets/generated/french-fries.dim_800x600.jpg",
    available: true,
  },
  {
    name: "Veg Sandwich",
    description: "Grilled sandwich with mixed vegetables",
    price: 50n,
    category: Category.fastFood,
    imageUrl: "/assets/generated/veg-sandwich.dim_800x600.jpg",
    available: true,
  },

  // Beverages
  {
    name: "Masala Chai",
    description: "Traditional Indian spiced tea",
    price: 20n,
    category: Category.beverages,
    imageUrl: "/assets/generated/masala-chai.dim_800x600.jpg",
    available: true,
  },
  {
    name: "Sweet Lassi",
    description: "Refreshing sweet yogurt drink",
    price: 50n,
    category: Category.beverages,
    imageUrl: "/assets/generated/sweet-lassi.dim_800x600.jpg",
    available: true,
  },
  {
    name: "Salted Lassi",
    description: "Cool and savory yogurt drink",
    price: 50n,
    category: Category.beverages,
    imageUrl: "/assets/generated/salted-lassi.dim_800x600.jpg",
    available: true,
  },
  {
    name: "Cold Coffee",
    description: "Chilled coffee with ice cream",
    price: 70n,
    category: Category.beverages,
    imageUrl: "/assets/generated/cold-coffee.dim_800x600.jpg",
    available: true,
  },
  {
    name: "Mango Shake",
    description: "Thick and creamy mango milkshake",
    price: 80n,
    category: Category.beverages,
    imageUrl: "/assets/generated/mango-shake.dim_800x600.jpg",
    available: true,
  },

  // Sweets
  {
    name: "Gulab Jamun",
    description: "Soft milk dumplings in sugar syrup (2 pcs)",
    price: 40n,
    category: Category.sweets,
    imageUrl: "/assets/generated/gulab-jamun.dim_800x600.jpg",
    available: true,
  },
  {
    name: "Rasgulla",
    description: "Spongy cottage cheese balls in syrup (3 pcs)",
    price: 50n,
    category: Category.sweets,
    imageUrl: "/assets/generated/rasgulla.dim_800x600.jpg",
    available: true,
  },
  {
    name: "Jalebi",
    description: "Crispy spiral sweets soaked in syrup (100g)",
    price: 60n,
    category: Category.sweets,
    imageUrl: "/assets/generated/jalebi.dim_800x600.jpg",
    available: true,
  },
  {
    name: "Ras Malai",
    description: "Cottage cheese patties in sweetened milk (2 pcs)",
    price: 70n,
    category: Category.sweets,
    imageUrl: "/assets/generated/ras-malai.dim_800x600.jpg",
    available: true,
  },
];
